name: Build and Deploy

on:
  workflow_dispatch:
    inputs:
      release_build:
        type: boolean
        required: false
        default: false
        description: Is Release Build ?
  push:

env:
  MAVEN_ARTIFACTORY_URL: ${{ vars.MAVEN_ARTIFACTORY_URL }}

jobs:
  run-snapshot-pipeline:
    uses: austinonthenet-org/shared-workflows/.github/workflows/build_and_deploy.yml@main

