name: Snapshot Build Workflow

on:
  workflow_dispatch:
    inputs:
      release_build:
        type: boolean
        required: false
        default: false
        description: Is Release Build ?
  push:


jobs:
  
  run-snapshot-pipeline:
    uses: austinonthenet/shared-workflows/.github/workflows/maven_snapshot.yml@main

